;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Class.Archer",DevComment="")
+GameplayTagList=(Tag="Class.Assassin",DevComment="")
+GameplayTagList=(Tag="Class.Mage",DevComment="")
+GameplayTagList=(Tag="Class.Warrior",DevComment="")
+GameplayTagList=(Tag="Race.Elf",DevComment="")
+GameplayTagList=(Tag="Race.Human",DevComment="")
+GameplayTagList=(Tag="Race.Orc",DevComment="")
+GameplayTagList=(Tag="Race.Undead",DevComment="")

